# Generated by Django 4.2.6 on 2023-10-31 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='user_name', max_length=50),
            preserve_default=False,
        ),
    ]
