# Generated by Django 4.2.6 on 2023-11-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_user_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dpi', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('reason', models.CharField(max_length=1000)),
            ],
        ),
    ]
