# Generated by Django 4.2.6 on 2023-11-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_requestappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('membership', models.IntegerField()),
                ('specialty', models.CharField(max_length=50)),
                ('others', models.CharField(max_length=1000)),
            ],
        ),
    ]
